---
- name: Ubuntu-specficic pkg mgmt
  hosts: all
  vars:
    sysadmin_groups: sudo
  vars_files:
    - /home/frank/ansible/variables/become_vars.yaml
  gather_facts: true
  become: true
  tasks:
# Update our system
    - name: Update all packages to the latest version using apt
      when: ansible_distribution == 'Ubuntu'
      apt:
        upgrade: dist
        update_cache: true
        cache_valid_time: 1200
# Install packages
    - name: Install Ubuntu-specific stuff
      package:
        name:
        - inetutils-traceroute
        - lynx
        - whois
        state: present
      when: ansible_distribution == 'Ubuntu'
# Remove some too
    - name: uninstall cloud-init and UFW from ubuntu
      package:
        name:
          - cloud-init
          - ufw
        state: absent
      when: ansible_distribution == 'Ubuntu'
