---
- name: Generic package management
  hosts: all
  vars:
#    source_gitkey: ~/.ssh/sshportal-gitlab.key
#    dest_gitkey_sysadmin: /home/sysadmin/.ssh/sshportal-gitlab.key
    sysadmin_groups: sudo
  vars_files:
    - /home/frank/ansible/variables/become_vars.yaml
  gather_facts: true
  become: true

  tasks:
    - name: Install a few packages
      ansible.builtin.package:
         name:
         - nano
         - net-tools
         - htop
         - iotop
         - glances
         - screen
         - zip
         - unzip
         - git
         - rkhunter
         state: present
